services:
  - type: web
    name: coding-meme-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    # Add system packages required for Pillow and other libraries
    systemPackages:
      - libjpeg-dev
      - zlib1g-dev
      - libpng-dev
      - libtiff-dev
      - libfreetype6-dev
      - webp
      - liblcms2-dev
      - libwebp-dev
      - tcl8.6-dev
      - tk8.6-dev
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
