services:
  - type: web
    name: flask-meme-generator
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: your_super_secure_random_key
