services:
  - type: web
    name: coding-meme-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    # Optional: If you need a specific Python version, add it here
    # pythonVersion: 3.9.18 # Example
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      # Add other environment variables if needed
